language: node_js
node_js:
  - '6'
addons:
  sauce_connect: true
  code_climate:
    repo_token: d92e680b8632754fe9b7dea8ec25b9a59f72804e226a171ca4b0a95b12f438e9
before_install:
  - gem install compass
install:
  - 'npm install -g npm@2'
  - 'npm install'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script:
  - 'grunt test'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && grunt e2e-sauce || false'
after_script:
  - codeclimate < test/reports/coverage/*/lcov.info
env:
  global:
    - secure: BrEVqXCOV40SehtQRfj5jyjS0oaxm5GkDENgkqYfSK7x3Y/DY+R0oV5dgQOx+AefyOi3VGXsMEQ9I9QdxoHEVvieWLzkYVqCvucte+gjtxI9cdKEpfrdwWZINr3JszniXdPpY47ImrB24rciUwE2Lrn6B/q22+/kfJjO5goMGdi1mdhPT/d3nb/bm+81FeW+z2AlA2VdJB/zaJvNO7fbYgBCHdo5vFoXh3PQ79MF1icADuvMttn8qfg5Ge45lcHSZORLaZ/hhQCdubWPhjYKtNCavyMDy9hDHKtKqsB0o0iBKGJWIJkiYe8rVc9oDxSzftOwcOv7FpPhSvUDZUc9x0alxmJ2v21Q6Epn/YhZJhQFxsbjHQPy3vUlb6obgJ4ZQy/tPIwChOM3judF/vtxSRcdsGDaD/fUY9p37xzd6lG330xWgKxKOHn536kpzI+1/7NMWRF1QM6gjP6tjMjMHCng7CnKAFzzyldJiZA8AltXZoa+g3dVJn7uJK0vILyALlq3UPTDmcQzzrudlrqTrNoY5oNL+MNpcafmBlXndSPQ3X86Y7BKnYHRZQM4X1o90O3HWUbJ4dUscPhbmKgwDTELvPgYYcADAG+0UV/0ZziHrw+BKg98Mx15eyr2W0Za5cjSEH7UHUl1qt7vIB3Vjis7sCGZG7g2ILUgnp4I6SE=
    - secure: HzLFrTR0u/kUxPIhAnCh/z7uUcy38tFLbut7gBXfHr2E0iBOWJducPG3IrPkccRz/9aidZAYFmtNXzw536cXWpLM0rnd/jYRfY72tghNgZkAlvaajyw5ajDM4d6ur0iC5Fhjwz/1rdKnFbu3+9xNHKtb2wldi5AUTG/3cummdS+mhYMVhL3iChltRWTUhvsNRjEBDvhfYM/2f9S9AS69PcU5nRKxGWf2j43rVKtlGA/WHX1TcggnDiXdc0Ap7GzJFsdB+Aqe54eXFnuDPZEOz8DjnogQ82/mxug0LwTZrmhbxbG7QJi3RxhiQSfxEDPVRVrVU5H1kqBOkl4SS2W2Qd/QYTVBakh5s6BuAxYTY+lmqyMm3d97T0U76KXciOwt6fo29oCEHEsb+Cp+RD8R/iesIwyovTIVus9ujxzSkepnrCTg2ERPTm4B6ycPJIxK2QmPEBXHjEDATjSP0FLEbw9GVZ70uXUNGKgN/Ib6DQb32CKIWOtDCzy2WGI2eMM/lpql6nUU6pof9EqgNCxrP19gv2MdBWs2z4pLWirc6dZdf86RNlpsK1DMF+pu2h5m48NT6glllFEP9LozdaPafDH2PJOjf5azCmSHrSM2zlo0Axhvu6Z4y5oJ35148ST1SjtLcKlPsuwWNDkeRZgmckOyCvOJxekaanc0Zpxql98=
sudo: false
